# Generated by Django 6.0.1 on 2026-06-20 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('INSTITUTION', 'Institution'), ('TEACHER', 'Teacher'), ('SUBJECT', 'Subject')], default='INSTITUTION', max_length=16)),
                ('period', models.CharField(choices=[('MONTHLY', 'Monthly'), ('SEMESTER', 'Semester'), ('CUSTOM', 'Custom')], default='MONTHLY', max_length=16)),
                ('file_format', models.CharField(choices=[('PDF', 'PDF'), ('XLSX', 'Excel')], default='PDF', max_length=8)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('file', models.FileField(blank=True, null=True, upload_to='analytics_reports/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='READY', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_reports', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_reports', to='institutions.institution')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['institution', 'created_at'], name='analytics_a_institu_69e979_idx')],
            },
        ),
        migrations.CreateModel(
            name='InstitutionDailySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('active_students', models.PositiveIntegerField(default=0)),
                ('daily_active_users', models.PositiveIntegerField(default=0)),
                ('learning_minutes', models.PositiveIntegerField(default=0)),
                ('avg_quiz_score', models.FloatField(default=0.0)),
                ('assignment_completion_rate', models.FloatField(default=0.0)),
                ('avg_mastery', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_snapshots', to='institutions.institution')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['institution', 'date'], name='analytics_i_institu_257691_idx')],
                'constraints': [models.UniqueConstraint(fields=('institution', 'date'), name='uniq_inst_snapshot_per_day')],
            },
        ),
    ]
