# Generated by Django 6.0.1 on 2026-06-20 14:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_mastery', models.FloatField(default=0.0)),
                ('topics_tracked', models.PositiveIntegerField(default=0)),
                ('weak_topic_count', models.PositiveIntegerField(default=0)),
                ('pace', models.CharField(choices=[('slow', 'Slow'), ('steady', 'Steady'), ('fast', 'Fast')], default='steady', max_length=10)),
                ('preferred_study_time', models.TimeField(default='20:00')),
                ('daily_minutes_target', models.PositiveIntegerField(default=60)),
                ('last_computed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('total_minutes', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=12)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StudyRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('learn', 'Learn'), ('revise', 'Revise'), ('practice', 'Practice'), ('prerequisite', 'Prerequisite')], max_length=16)),
                ('title', models.CharField(max_length=160)),
                ('message', models.CharField(blank=True, default='', max_length=400)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('dismissed', 'Dismissed')], db_index=True, default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to='academics.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('start_time', models.TimeField()),
                ('duration_min', models.PositiveIntegerField(default=30)),
                ('activity_type', models.CharField(choices=[('revision', 'Revision'), ('quiz', 'Quiz'), ('practice', 'Practice'), ('notes', 'Notes')], default='revision', max_length=12)),
                ('title', models.CharField(max_length=160)),
                ('completed', models.BooleanField(default=False)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='ai_learning.studyplan')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_sessions', to='academics.topic')),
            ],
            options={
                'ordering': ['order', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='WeakTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weak_score', models.FloatField(default=0.0)),
                ('mastery', models.FloatField(default=0.0)),
                ('accuracy', models.FloatField(default=0.0)),
                ('band', models.CharField(choices=[('beginner', 'Beginner'), ('developing', 'Developing'), ('proficient', 'Proficient'), ('mastered', 'Mastered')], default='beginner', max_length=12)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('computed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_weak_for', to='academics.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_weak_topics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-weak_score'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='generate', max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_rec_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='ai_learning_user_id_632ae2_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='studyplan',
            index=models.Index(fields=['user', '-date'], name='ai_learning_user_id_c983e1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studyplan',
            unique_together={('user', 'date')},
        ),
        migrations.AddIndex(
            model_name='studyrecommendation',
            index=models.Index(fields=['user', 'status', '-priority'], name='ai_learning_user_id_e7928c_idx'),
        ),
        migrations.AddIndex(
            model_name='weaktopic',
            index=models.Index(fields=['user', '-weak_score'], name='ai_learning_user_id_ceab40_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='weaktopic',
            unique_together={('user', 'topic')},
        ),
    ]
