# Generated by Django 6.0.1 on 2026-06-20 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(max_length=32)),
                ('target_id', models.CharField(max_length=64)),
                ('flag_type', models.CharField(choices=[('nsfw', 'NSFW'), ('duplicate', 'Duplicate'), ('policy', 'Policy violation'), ('low_quality', 'Low quality'), ('copyright', 'Copyright')], max_length=32)),
                ('severity', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flags_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['flag_type'], name='moderation__flag_ty_408f0f_idx'), models.Index(fields=['is_active'], name='moderation__is_acti_55e906_idx'), models.Index(fields=['target_type', 'target_id'], name='moderation__target__e03551_idx')],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('content', 'Content'), ('question', 'Question'), ('comment', 'Comment'), ('user', 'User'), ('institution', 'Institution'), ('other', 'Other')], max_length=32)),
                ('target_id', models.CharField(max_length=64)),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('abuse', 'Abuse / Harassment'), ('cheating', 'Cheating'), ('copyright', 'Copyright'), ('other', 'Other')], max_length=32)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewing', 'Reviewing'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='open', max_length=16)),
                ('resolved_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='moderation__status_3fc7e7_idx'), models.Index(fields=['reason'], name='moderation__reason_460c2e_idx'), models.Index(fields=['target_type', 'target_id'], name='moderation__target__dc17d8_idx'), models.Index(fields=['created_at'], name='moderation__created_7bb7e8_idx')],
            },
        ),
    ]
